### ISSUE TITLE
What happened to this project?

### ISSUE THREAD

**Issue by Hoernchen** [greatscottgadgets/amalthea#6]
I have just discovered this and it kinda looks like a great fgpa/atrf dev board - after browsing twitter for a bit it looks like at least iq rx streaming to GR/fossphor was actually validated with real hardware, are there any known issues? I guess this project, just like so many other projects, just stalled due to part shortages?

**Comment by mossmann** [comment]
The project is still progressing slowly. The current incarnation of hardware is a small add-on for Cynthion: https://github.com/greatscottgadgets/amalthea-hardware

@mndza has been working on DSP gateware here: https://github.com/mndza/dsp_sandbox
